# Generated by Django 5.0.1 on 2024-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProductos', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
